name: Terraform EC2 Setup and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Capture EC2 Public IP
      run: |
        EC2_IP=$(terraform output -raw instance_ip)
        echo "EC2_IP captured: $EC2_IP"
        if [[ -z "$EC2_IP" ]]; then
          echo "Erro: IP da instância EC2 não encontrado"
          exit 1
        fi
        echo "$EC2_IP" > $GITHUB_WORKSPACE/ec2_ip.txt
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Read EC2 IP from File
      run: |
        if [[ ! -f "$GITHUB_WORKSPACE/ec2_ip.txt" ]]; then
          echo "Erro: Arquivo ec2_ip.txt não encontrado"
          exit 1
        fi
        EC2_IP=$(cat $GITHUB_WORKSPACE/ec2_ip.txt)
        echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: SSH into EC2 and Deploy Application
      run: |
        echo "Deploying application to EC2 instance..."
        ssh -o StrictHostKeyChecking=no -i deployer-key.pem ubuntu@$EC2_IP << 'EOF'
          set -e
          echo "Updating instance..."
          sudo apt-get update -y
          sudo apt-get install -y docker.io
          
          echo "Creating app directory..."
          mkdir -p /home/ubuntu/app
          
          echo "Downloading application files from S3..."
          curl -o /home/ubuntu/app/requirements.txt https://s3.us-east-1.amazonaws.com/YOUR_BUCKET/requirements.txt
          curl -o /home/ubuntu/app/app.py https://s3.us-east-1.amazonaws.com/YOUR_BUCKET/app.py
          curl -o /home/ubuntu/app/Dockerfile https://s3.us-east-1.amazonaws.com/YOUR_BUCKET/Dockerfile
          
          echo "Building Docker image..."
          cd /home/ubuntu/app
          sudo docker build -t myapp .
          
          echo "Running Docker container..."
          sudo docker run -d -p 80:80 myapp
        EOF
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        EC2_IP: ${{ env.EC2_IP }}