name: Deploy EC2 Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      run: |
        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create EC2 instance
      run: |
        aws ec2 run-instances \
          --image-id ami-0ac80df6eff0e70b5 \  # Substitua pela ID correta da AMI
          --count 1 \
          --instance-type t2.micro \
          --key-name minha-chave-ec2 \
          --security-group-ids sg-xxxxxxxx \  # Substitua pelo ID do seu Security Group
          --subnet-id subnet-xxxxxxxx \  # Substitua pelo ID da sua Subnet
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MinhaInstanciaEC2}]'

    - name: Get EC2 instance public IP
      id: get-ip
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --query 'Reservations[0].Instances[0].InstanceId' --output text)
        PUBLIC_IP=$(aws ec2 describe-instances --instance-id $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
        echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

    - name: Deploy to EC2 instance
      run: |
        # Conectando via SSH e executando os comandos de deploy
        ssh -i minha-chave-ec2.pem ubuntu@$PUBLIC_IP << 'EOF'
            echo "Iniciando deploy..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo docker --version
            cd /home/ubuntu/app
            sudo docker build -t my-python-app .
            sudo docker run -d -p 5000:5000 my-python-app
            echo "Deploy concluído"
        EOF
