name: Terraform EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout o repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configurar as credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Instalar o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 4: Inicializar o Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 5: Rodar o Terraform Apply para criar a instância EC2
      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve
          sleep 30 
      
      - name: Verificar se a saída da instância EC2 está sendo gerada
        run: |
          terraform output -raw instance_ip
      # Step 6: Obter o IP público da instância EC2
      - name: Get EC2 instance IP
        id: ec2_ip
        run: |
          IP=$(terraform output -raw instance_ip)
          echo "EC2 IP: $IP"
          echo "EC2_IP=$IP" >> $GITHUB_ENV
    
      - name: Verificar IP da instância EC2
        run: |
            echo "Valor da variável EC2_IP: ${{ env.EC2_IP }}"
        
      - name: SSH into EC2 and deploy
        run: |
            echo "Conectando no EC2 com o IP: ${{ env.EC2_IP }}"
            echo "" > private_key.pem
            chmod 600 private_key.pem
            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_IP }} << 'EOF'
              echo "Iniciando deploy..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo docker --version
              cd /home/ubuntu/app
              sudo docker build -t my-python-app .
              sudo docker run -d -p 5000:5000 my-python-app
              echo "Deploy concluído"
            EOF