name: Terraform EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout o repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configurar as credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Instalar o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 4: Inicializar o Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 5: Rodar o Terraform Apply para criar a instância EC2
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
      
      # Step 6: Obter o IP público da instância EC2
      - name: Get EC2 Public IP
        id: get_ip
        working-directory: ./terraform
        run: |
          EC2_IP=$(terraform output -raw instance_ip 2>/dev/null | tr -d '\n')
          echo "EC2 IP: $EC2_IP"
          if [ -z "$EC2_IP" ]; then
          echo "Erro: Não foi possível encontrar o IP público da instância EC2"
          exit 1
          fi
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV
      # Step 7: Verificar se a instância EC2 está acessível
      - name: Wait for EC2 to be accessible
        run: |
          until ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_IP }} "echo EC2 is accessible"; do
            echo "Aguardando a instância EC2 ficar acessível..."
            sleep 30
          done

      # Step 8: SSH into EC2 and deploy
      - name: SSH into EC2 and deploy
        run: |
            echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
            chmod 600 private_key.pem
            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_IP }} << 'EOF'
              echo "Iniciando deploy..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo docker --version
              cd /home/ubuntu/app
              sudo docker build -t my-python-app .
              sudo docker run -d -p 5000:5000 my-python-app
              echo "Deploy concluído"
            EOF
