name: Terraform EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout o repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configurar o AWS CLI para acessar sua conta
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Instalar o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 4: Inicializar o Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 5: Rodar o Terraform Apply para criar a instância EC2
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      # Step 6: Obter o IP público da instância EC2 e salvar em um arquivo
      - name: Get EC2 Public IP
        working-directory: ./terraform
        run: |
          EC2_IP=$(terraform output -raw instance_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
          echo "EC2 IP: $EC2_IP"
          if [ -z "$EC2_IP" ]; then
            echo "Erro: Não foi possível encontrar o IP público da instância EC2"
            exit 1
          fi
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV  # Armazena o IP no arquivo de ambiente

      # Step 7: Deploy Python app on EC2
      - name: Deploy Python app on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_PRIVATE_KEY }}" ubuntu@${{ env.EC2_IP }} << 'EOF'
            echo "Iniciando deploy..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo docker --version
            cd /home/ubuntu/app
            sudo docker build -t my-python-app .
            sudo docker run -d -p 5000:5000 my-python-app
            echo "Deploy concluído"
          EOF
