name: Terraform EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Get EC2 Public IP and Instance ID
        id: ec2_info
        working-directory: ./terraform
        run: |
          EC2_IP=$(terraform output -raw instance_ip)
          EC2_INSTANCE_ID=$(terraform output -raw instance_id)
          echo "EC2 IP: $EC2_IP"
          echo "EC2_INSTANCE_ID=$EC2_INSTANCE_ID" >> $GITHUB_ENV
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

      - name: Deploy Python app on EC2 using EC2 Instance Connect
        run: |
          echo "Conectando no EC2 com o IP: ${{ env.EC2_IP }}"
          
          # Enviar chave pública via EC2 Instance Connect
          aws ec2-instance-connect send-ssh-public-key \
            --region us-east-1 \
            --instance-id ${{ env.EC2_INSTANCE_ID }} \
            --availability-zone us-east-1a \
            --instance-os-user ubuntu \
            --ssh-public-key file://~/.ssh/id_rsa.pub

          # Conectar via SSH após enviar chave pública
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << 'EOF'
            echo "Iniciando deploy..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo docker --version
            cd /home/ubuntu/app
            sudo docker build -t my-python-app .
            sudo docker run -d -p 5000:5000 my-python-app
            echo "Deploy concluído"
          EOF